/*
 * This source file was generated by the Gradle 'init' task
 */
package flink.self.traning;

import org.junit.jupiter.api.Test;

import flink.self.traning.statelessTransformation.FilterApp;

import static org.junit.jupiter.api.Assertions.*;

class FirstAppTest {
    @Test void appHasAGreeting() {
        FilterApp classUnderTest = new FilterApp();
    }
}
